# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ithehero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('bg', 'Bulgarian')], max_length=2),
        ),
    ]
