# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ithehero', '0003_blog_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='asd', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
