# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ithehero', '0004_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('a', 'Article'), ('p', 'Project'), ('b', 'About')], default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='media/images/noimage.jpg', upload_to='media/images'),
        ),
    ]
