# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ithehero', '0005_auto_20170316_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='media/images/noimage.jpg', upload_to='images'),
        ),
    ]
