# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-19 18:49
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ithehero', '0008_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
