# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ithehero', '0009_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('a', 'Article'), ('p', 'Project'), ('b', 'About'), ('i', 'Intro')], default='a', max_length=1),
        ),
    ]
