# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ithehero', '0012_auto_20170327_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='exhibit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ithehero.Exhibit'),
        ),
    ]
