# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ithehero', '0013_auto_20170327_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='image',
            field=models.ImageField(default='images/noimage.jpg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='image',
            field=models.ImageField(default='images/noimage.jpg', upload_to='images'),
        ),
    ]
