# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 20:16
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ithehero', '0014_auto_20170330_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
