# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-02 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ithehero', '0015_exhibit_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art',
            old_name='image',
            new_name='picture',
        ),
        migrations.AddField(
            model_name='art',
            name='audio',
            field=models.FileField(default='audio/default.mp3', upload_to='audio'),
        ),
        migrations.AddField(
            model_name='art',
            name='company',
            field=models.ImageField(default='images/noimage.jpg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='art',
            name='game',
            field=models.ImageField(default='images/noimage.jpg', upload_to='images'),
        ),
    ]
