# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-02 13:03
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ithehero', '0016_auto_20170402_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='stats',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
